### ISSUE TITLE
@at-root does not work anymore. Foundation scss is wrong compiled

### ISSUE THREAD

**Issue by thomas-nommensen** [madskristensen/WebCompiler#226] opened 2016-05-19 08:54 UTC
### Installed product versions
Visual Studio:2015 community
This extension: 1.1.32

### Description
The @at-root directive does not work in the current version. Instead of emitting the rule to the root of documnet, it is nested in the current selector. Older versions did the job fine.

Where can i get an older version of the installer (e.g. from beginning of the year)?

**Comment by madskristensen** [comment] 2016-05-19 16:29
I don't keep any old versions around anywhere. This is a bug in libsass and a dupe of #217

**Closed by madskristensen** 2016-05-19 16:29 UTC
