### ISSUE TITLE
Font escape sequences corrupted

### ISSUE THREAD

**Issue by thecartman82** [madskristensen/WebCompiler#78] opened 2015-08-17 14:13 UTC
The problem arises during compilation of font awesome's sass into css.

Original source (sass):

![image](https://cloud.githubusercontent.com/assets/13422207/9306764/98c4997e-44fa-11e5-8e12-6a5bbc89675b.png)

Produced css:

![image](https://cloud.githubusercontent.com/assets/13422207/9306726/707a41f8-44fa-11e5-952c-24e5d4a1d628.png)

Could be related to #74 

I looked around and didn't see anyone else with this issue, so it could also be something I screwed up.

**Comment by madskristensen** [comment] 2015-08-17 15:06
Yes, this is a dupe of #74

**Closed by madskristensen** 2015-08-17 15:06 UTC

**Comment by madskristensen** [comment] 2015-08-17 15:07
It will be fixed when I move the sass compiler to use node-sass instead of libsassnet

**Comment by luissardon** [comment] 2016-12-29 21:24
![image](https://cloud.githubusercontent.com/assets/4295163/21555122/399b0af0-cde3-11e6-86a9-618a6802ba90.png)

Looks like problem has re-emerged
