### ISSUE TITLE
more than 1 class on div element compiles to css incorrectly

### ISSUE THREAD

**Issue by derek1982** [madskristensen/WebCompiler#247] opened 2016-07-26 15:59 UTC
### Installed product versions
- Visual Studio 2015: Community Edition, Version 14.0.25123.00 Update 2
- Web Compiler version 1.11.315

### Description

Hi, I have discovered a small bug when scss targets more than 1 class on an element. 

Example. 
if an HTML section or div has more than 1 class applied, e.g. class=”content-block style-1”

and in the scss file we have. 

```
.content-block{    
	.style-1 {
		background-color: #58C9EB; 
	} 
}
```

then it compiles to, 

`.content-block .style-1{background-color:#58c9eb;}`

the gap between the 2 classes in the css output, prevents it rendering the background color in the browser (due to the classes being on the same element, they require that there isn't a space in the css).

Apart from this small bug, Web compiler is excellent. 
Thank you for taking the time to create it.

**Comment by duncansmart** [comment] 2016-08-01 11:33
Not a bug. Consult the [SASS syntax docs](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#parent-selector). Looks like you should be using the `&` parent selector to get the result you want:

    .content-block {    
        &.style-1 {
            background-color: #58C9EB; 
        } 
    }

**Comment by madskristensen** [comment] 2016-08-01 15:15
Thanks for the explanation @duncansmart. Closing issue

**Closed by madskristensen** 2016-08-01 15:15 UTC
