### ISSUE TITLE
Add support for autoprefixer

### ISSUE THREAD

**Issue by kingmotley** [madskristensen/WebCompiler#35] opened 2015-07-20 20:48 UTC
It would be nice if autoprefixing was an option like it was in WE 2013.

**Comment by GProulx** [comment] 2015-07-21 00:25
This request was already discussed on #4

**Comment by kingmotley** [comment] 2015-07-21 16:54
What about using https://github.com/digitalcreations/autoprefixer?

**Comment by madskristensen** [comment] 2015-09-23 18:28
Duplicate of #4

**Comment by madskristensen** [comment] 2015-09-23 20:08
Duplidate of #4

**Comment by madskristensen** [comment] 2015-09-23 22:44
I found a plugin to the LESS compiler, so this is doable. Adding it now

**Closed** 2015-09-23 22:58 UTC
Labels: enhancement
