### ISSUE TITLE
Problem with compiling SCSS files in the newest version

### ISSUE THREAD

**Issue by Nick0n** [madskristensen/WebCompiler#177] opened 2016-01-21 10:30 UTC
Saving SCSS file doesn't run compiler. I'm getting an error in the Output during compilation process:

21.01.2016 10:47:20: System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.Combine(String path1, String path2)
   at WebCompiler.SassDependencyResolver.UpdateFileDependencies(String path) in C:\projects\webcompiler\src\WebCompiler\Dependencies\SassDependencyResolver.cs:line 45
   at WebCompiler.DependencyService.GetDependencies(String projectRootPath, String sourceFile) in C:\projects\webcompiler\src\WebCompiler\Dependencies\DependencyService.cs:line 50
   at WebCompiler.ConfigFileProcessor.SourceFileChanged(String configFile, String sourceFile, String projectPath, HashSet`1 compiledFiles) in C:\projects\webcompiler\src\WebCompiler\Config\ConfigFileProcessor.cs:line 116
   at WebCompilerVsix.CompilerService.<>c__DisplayClass7_0.<SourceFileChanged>b__0(Object o) in C:\projects\webcompiler\src\WebCompilerVsix\CompilerService.cs:line 101

**Comment by tankmc1989** [comment] 2016-01-21 11:13
Yes i am having the same issues Anyone have any suggestions?

**Comment by PaulVrugt** [comment] 2016-01-21 16:24
Could you post the way of registering imports in the scss file here? I mean: paste the part of the contents of the scss file which fails in which the imports are defined so I can check if there is a problem with the way we detect imports. Apparently it detects an import, and tries to locate this import file, but it generates an illegal path.

**Comment by PaulVrugt** [comment] 2016-01-21 16:58
Could it be that are using absolute paths in the imports?

**Comment by madskristensen** [comment] 2016-01-21 18:32
@Nick0n @tankmc1989, can you please try the CI build 1.10.299 too see if it's fixed? Download it here http://vsixgallery.com/extension/148ffa77-d70a-407f-892b-9ee542346862/

**Comment by matthewpavkov** [comment] 2016-01-21 19:21
Yeah, I'm having the same issue. I'll try the 1.10 build and report back. Not using absolute paths anywhere.

**Comment by matthewpavkov** [comment] 2016-01-21 19:34
Well, the vsixgallery.com website wasn't working for me, but it looks like the 1.10.299 update came through Visual Studio. I installed it and things are working now. I'll report back if I run into this again. Thanks!

**Comment by matthewpavkov** [comment] 2016-01-21 19:42
Spoke too soon, I'm still getting the same error as the one posted above. As that happens, I also get an alert saying that the `compilerconfig.json` is invalid. This is the contents of that file:

```[
    {
        "outputFile": "web/app/_assets/client.css",
        "inputFile": "web/app/_assets/client.scss"
    }
]```

And the contents of my `compilerconfig.defaults.json`:

```{
    "compilers": {
        "sass": {
            "includePath": "",
            "indentType": "space",
            "indentWidth": 2,
            "lineFeed": "crlf",
            "outputStyle": "nested",
            "Precision": 5,
            "relativeUrls": true,
            "sourceMapRoot": "",
            "sourceMap": false
        }
    },
    "minifiers": {
        "css": {
            "enabled": true,
            "termSemicolons": true,
            "gzip": false
        }
    }
}```

**Comment by Nick0n** [comment] 2016-01-21 19:43
For me it works fine, thanks!!!

**Comment by leniency** [comment] 2016-01-21 21:36
Not fixed here with 1.0.10.299 (reinstalled the version from CI). Appears to throw line 55 in SassDependencyResolver. I only have LESS files in my project, no sass/scss files anywhere. Running the LESS compilation task or recompiling via menus still works fine, just throws error when saving a less file.

   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.Combine(String path1, String path2)
   at WebCompiler.SassDependencyResolver.UpdateFileDependencies(String path) in C:\projects\webcompiler\src\WebCompiler\Dependencies\SassDependencyResolver.cs:line 55
   at WebCompiler.DependencyService.GetDependencies(String projectRootPath, String sourceFile) in C:\projects\webcompiler\src\WebCompiler\Dependencies\DependencyService.cs:line 50
   at WebCompiler.ConfigFileProcessor.SourceFileChanged(String configFile, String sourceFile, String projectPath, HashSet`1 compiledFiles) in C:\projects\webcompiler\src\WebCompiler\Config\ConfigFileProcessor.cs:line 116
   at WebCompilerVsix.CompilerService.<>c__DisplayClass7_0.<SourceFileChanged>b__0(Object o) in C:\projects\webcompiler\src\WebCompilerVsix\CompilerService.cs:line 101

**Comment by madskristensen** [comment] 2016-01-21 21:46
@leniency What's in your `@import` statements? Can you please share them. Sounds like our regex isn't catching some cases

**Comment by leniency** [comment] 2016-01-21 22:12
In the main file, these are the only imports. Down below that... lots.

    @import url("//fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,700italic,300,400,700");
    @import "bootstrap.less"; // Specific boostrap modules.
    @import "../../fontawesome/font-awesome.less"; // Font-Awesome
    @import "kendo.less"; // Kendo
    @import "enroller.less"; // Specific enroller modules.
    @import "theme.menu.less";
    @import "variables.less";

**Comment by matthewpavkov** [comment] 2016-01-21 22:34
If I remove this

```
@import url("//fonts.googleapis.com/css?family=Source+Sans+Pro:400,300,600,700,400italic,300italic,600italic,700italic,900");
```

Then things work. It's not handling `@import url` correctly, it's treating them like files.

**Comment by madskristensen** [comment] 2016-01-21 22:40
Thanks for all the detailed repro steps. I believe this is now fixed. An update will go out shortly

**Closed** 2016-01-21 22:39 UTC

**Comment by leniency** [comment] 2016-01-21 22:41
I can confirm that. Also didn't notice I had a @import in a comment as well that was causing the same issue with the regex.

I should note again that this is a LESS file and I have no sass or scss files in the project. Not sure the SassDependencyResolver should be scanning it? However, and sass files would run into the same issue.

**Comment by leniency** [comment] 2016-01-21 22:48
Just installed 1.10.300 - working. Thanks!

**Comment by matthewpavkov** [comment] 2016-01-21 22:56
Confirmed here too. Working with `scss` files. Thanks you!
