### ISSUE TITLE
LESS - Compile on save

### ISSUE THREAD

**Issue by markvantilburg** [madskristensen/WebCompiler#65] opened 2015-08-04 10:47 UTC
Compile on save compiles the current file, but also the files in the ```compilerconfig.json``` that have no dependencies on the currently saved file. 

While for files that have dependencies on the saved less file are not updated unless they are in ```compilerconfig.json```.

**Comment by markvantilburg** [comment] 2015-08-04 10:49
Also when saving a less file it would be nice if that was automatically added to the compiler config.

**Comment by madskristensen** [comment] 2015-08-04 16:04
That is by design. This is to make sure that any file that imports a partial file is updated when the partial is modified. I'll add a keyboard shortcut to make it super easy to add the currently edited file to `compilerconfig.json` without it prompts you with a SaveFileDialog

**Comment by markvantilburg** [comment] 2015-08-04 18:27
Why not hook the save command?
I guess when someone saves a .less file that they also want to compile that file. 

Maybe make it an configurable something like "Add saved .less files to .json on save if not in .json yet"

**Comment by madskristensen** [comment] 2015-08-04 18:49
Because compiling the LESS file could already be handled by other extensions, external apps or Gulp/Grunt

**Comment by madskristensen** [comment] 2015-08-04 18:50
I've just committed a new feature that lets you very easily add files to the .json file and kick of compilation. It is very similar to what Web Essentials 2013 did, except you have to hit a keyboard shortcut first (and only once per file) before compilation happens automatically on save.

**Closed by madskristensen** 2015-08-04 18:50 UTC

**Comment by markvantilburg** [comment] 2015-08-04 19:42
It's getting closer to the almost perfect 2013 solution :+1:

**Comment by madskristensen** [comment] 2015-08-04 20:00
Except that the WE2013 solution wasn't perfect in any way, IMO :)
