### ISSUE TITLE
SCSS Validation support for @at-root

### ISSUE THREAD

**Issue by travislaynewilson** [madskristensen/WebCompiler#218] opened 2016-05-11 18:15 UTC
### Installed product versions
- Visual Studio: 2015 Community
- This extension: 1.11.312

### Description
The Web Compiler engine does not appear to help Visual Studio validate SCSS's @at-root directive.

### Steps to recreate
Here's a code sample:
`.btn {
  &.btn-primary { color: red;
     @at-root fieldset btn.btn-primary { color: blue; }
  }
}`

### Current behavior
When working in a *.scss file, using the @at-root SCSS directive causes CSS3 validation errors. The SCSS document still compiles as expected, but other tasks like Format Document no longer work due t the validation error.

The validation error is: Validation (CSS 3.0): "at-root" is not a known "@" directive.

### Expected behavior
I'd expect the document to continue validating.

**Comment by madskristensen** [comment] 2016-05-11 18:17
Duplicate of #217

**Closed by madskristensen** 2016-05-11 18:17 UTC
