### ISSUE TITLE
LESS: Including another style set generates invalid CSS

### ISSUE THREAD

**Issue by bradlis7** [madskristensen/WebCompiler#41] opened 2015-07-22 19:58 UTC
In Web Essentials 2013, this wasn't an issue, but when I use the new Web Compiler in VS2015, I'm trying to use this code to copy styles from one element to another (using Bootstrap 3.x).

### My Site.less file

    @import (reference) "Bootstrap/mixins/alerts.less";
    @import (reference) "Bootstrap/alerts.less";
    .validation-summary-errors {
      .alert; .alert-danger;
    }

### Bootstrap/alerts.less

    .alert {
      padding: @alert-padding;
      margin-bottom: @line-height-computed;
      border: 1px solid transparent;
      border-radius: @alert-border-radius;

      // Headings for larger alerts
      h4 {
        margin-top: 0;
        // Specified for the h4 to prevent conflicts of changing @headings-color
        color: inherit;
      }
  
      // Provide class for links that match alerts
      .alert-link {
        font-weight: @alert-link-font-weight;
      }

      // Improve alignment and spacing of inner content
      > p,
      > ul {
        margin-bottom: 0;
      }
  
      > p + p {
        margin-top: 5px;
      }
    }
    // ... skipping
    .alert-danger {
      .alert-variant(@alert-danger-bg; @alert-danger-border; @alert-danger-text);
    }

### Bootstrap/mixins/alert.less:

    .alert-variant(@background; @border; @text-color) {
      background-color: @background;
      border-color: @border;
      color: @text-color;

      hr {
        border-top-color: darken(@border, 5%);
      }
      .alert-link {
        color: darken(@text-color, 10%);
      }
    }

### Site.css Output

This invalid CSS gets put at the very top of the generated file.

     {
      margin-top: 0;
      color: inherit;
    }
     {
      font-weight: bold;
    }
     {
      margin-bottom: 0;
    }
     {
      margin-top: 5px;
    }
     {
      border-top-color: #e4b9c0;
    }
     {
      color: #843534;
    }

I've also run into an issue where the file doesn't compile, but I don't get any sort of message, and nothing in the Output window I can see.

**Comment by madskristensen** [comment] 2015-07-28 00:19
Duplicate of #37

**Closed by madskristensen** 2015-07-28 00:19 UTC
