### ISSUE TITLE
Editing source maps in chrome workspace generates code but doesn't watch for changes and recompile

### ISSUE THREAD

**Issue by lindeberg** [madskristensen/WebCompiler#190] opened 2016-02-08 15:02 UTC
For example: changing styles [here](https://i.gyazo.com/a93a28960a9d97d3d6f6d11c0dac37fd.png), and saving, generates code in the .scss file. But I have to save the .scss file in Visual Studio as well for changes to take place and to update the css in chrome.

[VS environment](https://i.gyazo.com/d191eae8fa42fc887b903b1478b67f3a.png)

**Comment by madskristensen** [comment] 2016-02-08 16:14
Duplicate of #144

**Closed by madskristensen** 2016-02-08 16:14 UTC
Labels: duplicate
