### ISSUE TITLE
Suggestion: post-processor

### ISSUE THREAD

**Issue by CheloXL** [madskristensen/WebCompiler#51] opened 2015-07-26 00:08 UTC
Add a way to configure an executable that will run after the compilation has ran. In this way, I can add autoprefixer again (running from node, of course).
Maybe you can add this option to the bundler too (to run between bundling and minification).

**Comment by madskristensen** [comment] 2015-07-26 00:51
Why not just run Gulp if you're setting up node modules anyway?

**Comment by CheloXL** [comment] 2015-07-26 02:42
Never used gulp, and I just installed node to run autoprefixer. There is really no need for me to use node for anything. 
And hooking node on the post-build event is not an option, because that runs after the bundling/minification.

**Comment by kingmotley** [comment] 2015-07-28 15:12
Why aren't you doing bundling and minification in node?

**Comment by CheloXL** [comment] 2015-07-28 18:22
As I said, because I just installed node to run autoprefixer. I don't use node and I would like not to have to use it, but with autoprefixer removed from webessentials, I had no other choice.

**Comment by madskristensen** [comment] 2015-08-01 18:48
Duplicate of #35

**Closed by madskristensen** 2015-08-01 18:48 UTC

**Comment by madskristensen** [comment] 2015-09-23 22:52
Auto prefixer is coming to the LESS compiler. Adding it now
